[global]
sim_hours = 24
dt = 1.0
dtmeas = 120
meas_noise_std = 0.25
uex_bounds = [0, 166]
D_bounds = [0.2, 0.4]
PN_bounds = [0.2, 0.4]
SI_params = [-8.05, 0.70]
x_max = [17.5, 260, 220, 11.5 , 57]
u_en_max = 46
SI_max = 5e-4
y0 = [7.357, 133.115, 98.203, 8.657, 43.283]
init_cov_scale = 1
init_cov = [1, 3, 3, 1, 2, 1]
process_noise_factor =  0.0083
SI_process_noise = 0.33
SI_ekf_covar = 1e-5
SI_pf_covar = 1e-8

[00]
num_patients = 5
num_simulations = 100000

[01]
num_patients = 1000
n_pert = 5
c = 0.1
threshold = 0.1

[02]
sim_hours = 60
num_patients = 500
max_std = 0.4
num_std = 5
low_perc = 5
high_perc = 95
CI = 90
SI_scale = [0.75, 0.95]
change_SI = 3

[03]
sim_hours = 12
num_patients = 50
process_noise_factor = 1e-3
num_particles = [100, 200, 300, 400, 500, 750, 1000, 1500, 2000] 
# num_particles = [500]
plot_particles_idx = [0, 1, 3, 5, 6, 8] # 0 is the ekf
# plot_particles_idx = [0, 1, 2, 3]
low_perc = 5.0
high_perc = 95.0
CI = 90
converge_time = 500
deviations = [0.75, 0.90, 0.98, 1.02, 1.1, 1.25]
# deviations = [0.9, 1.1]
dev_perc = [-25, -10, -2, 2, 10, 25]
# dev_perc = [-10, 10]

[04]
sim_hours = 60
sim_hours_vary = 60
num_patients = 50
deviations = [0.9, 1.1]
dev_perc = [-10, 10]
SI_scale = [0.75, 0.95]
process_noise_factor = 0.0083
num_particles = [1410]
low_perc = 5.0
high_perc = 95.0
CI = 90
change_SI = 3